### ISSUE TITLE
[Issue]: Loop-back devices creation script not working in Openstack-helm

### ISSUE THREAD

**Issue by Alt-Shivam** [stannum-l/windwaker#7]
Hello @stannum-l  sir 
Sorry for opening this issue here.
But I don't have any other way to contact you

Just need your help to resolve this issue with openstack-helm Loop-back devices creation i.e [this](https://docs.openstack.org/openstack-helm/latest/install/multinode.html) and [this](https://docs.openstack.org/openstack-helm/latest/install/developer/deploy-with-ceph.html)

basically whenever I try to make loop-devices with them 
it throws a lot of errors

If you can share an ideal deployment guide or something like that 
I would be very thankful 

also if you need logs and list of errors 
than I can also share them

Thanks for reading this.
Shivam

**Comment by stannum-l** [comment]
Hello, @Alt-Shivam thanks for reaching out. However, this repository is not related to OpenStack-Helm. Please reach out on IRC and Slack links provided here: https://docs.openstack.org/openstack-helm/latest/troubleshooting/index.html#getting-help

Or please use the mailing list here https://wiki.openstack.org/wiki/Mailing_Lists.

Other folks and myself can provide assistance there.

Cheers,
Tin

**Comment by Alt-Shivam** [comment]
Thanks @stannum-l sir for reply.

**Comment by Alt-Shivam** [comment]
Sorry to say this @stannum-l  sir
but tried everything to resolve this.
asked the same question on slack and also talked to Gage Hugo sir but no satisfactory answer till now.
just trying for the last 2 months for some help.

will really appreciate If you could help me out in this.

**Comment by stannum-l** [comment]
I would suggest pinging Gage again or Chinasubbareddy Mallavarapu from the core team to assist with your Ceph issue. Also, have you considered looking into Rook?  Those Ceph charts out there may be old.
